# Generated by Django 4.1.5 on 2023-04-12 01:10

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Trailer'),
        ),
    ]
